spring:
  redis:
    host: localhost
    port: 6379
  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  datasource:
    hikari:
      jdbc-url: jdbc:h2:mem:testdb
      username: sa
      password:
  h2:
    console:
      enabled: true
